# Generated by Django 2.2.4 on 2019-08-27 18:11

import airquality.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0002_report_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipcodeLatLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5, validators=[airquality.models.validate_zipcode])),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('datetime_updated', models.DateTimeField()),
            ],
        ),
    ]
