# Generated by Django 2.2.4 on 2019-08-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0003_zipcodelatlong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
    ]
