# Generated by Django 2.2.4 on 2019-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0005_report_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AQI_green_days', models.IntegerField()),
                ('AQI_yellow_days', models.IntegerField()),
                ('AQI_orange_days', models.IntegerField()),
                ('AQI_red_days', models.IntegerField()),
                ('AQI_purple_days', models.IntegerField()),
                ('AQI_maroon_days', models.IntegerField()),
                ('raw_data', models.FileField(upload_to='')),
            ],
        ),
    ]
