# Generated by Django 2.2.4 on 2019-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0006_airqualityreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualityreport',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='airqualityreport',
            name='binary_raw_file',
            field=models.BinaryField(null=True),
        ),
    ]
