# Generated by Django 2.2.4 on 2019-09-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0007_auto_20190905_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipcodeLatLong',
        ),
        migrations.AddField(
            model_name='airqualityreport',
            name='userRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airquality.Report'),
        ),
    ]
